package com.example.soymusicreviewapp.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF7A2AD5)
val onPrimaryLight = Color(0xFFFFFFFF) // WHITE
val primaryContainerLight = Color(0xFF944BF0)
val onPrimaryContainerLight = Color(0xFFE9D4FF)
val secondaryLight = Color(0xFFA461C1) // LIGHT VIOLET
val onSecondaryLight = Color(0xFFE9D4FF) // LIGHT VIOLET LETTER
val secondaryContainerLight = Color(0xFF8E19B8)
val onSecondaryContainerLight = Color(0xFF695E92)
val tertiaryLight = Color(0xFF504978) // GREY
val onTertiaryLight = Color(0xFF444444) // dark grey
val tertiaryContainerLight = Color(0xFF7B5E96) // Dark violet
val onTertiaryContainerLight = Color(0xFFFF86CA)
val errorLight = Color(0xFFED3F3F)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFAF34DD)
val onErrorContainerLight = Color(0xFFFFF6FC)
val backgroundLight = Color(0xFF695E92) //BLUE 2
val onBackgroundLight = Color(0xFFFFFFFF)
val surfaceLight = Color(0xFF64779C) // darkblue
val onSurfaceLight = Color(0xFF695E92)
val surfaceVariantLight = Color(0xFF714D3B) // Dark yellow
val onSurfaceVariantLight = Color(0xFF946A2D) // light yellow
val outlineLight = Color(0xFF74787A)
val outlineVariantLight = Color(0xFFC3C7C9)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF313030)
val inverseOnSurfaceLight = Color(0xFFF4F0EF)
val inversePrimaryLight = Color(0xFFD8B9FF)
val surfaceDimLight = Color(0xFF3C3D5A) // Vclaro
val surfaceBrightLight = Color(0xFFE9D4FF)// VCLAROLETRA
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF6F3F2)
val surfaceContainerLight = Color(0xFFF1EDEC)
val surfaceContainerHighLight = Color(0xFFEBE7E7)
val surfaceContainerHighestLight = Color(0xFFE7AF12)


val primaryDark = Color(0xFFD8B9FF)
val onPrimaryDark = Color(0xFF450086)
val primaryContainerDark = Color(0xFFAF71FF)
val onPrimaryContainerDark = Color(0xFF1E0041)
val secondaryDark = Color(0xFFEEB1FF)
val onSecondaryDark = Color(0xFF53006F)
val secondaryContainerDark = Color(0xFF8E19B8)
val onSecondaryContainerDark = Color(0xFFF2BEFF)
val tertiaryDark = Color(0xFFFFAFD8)
val onTertiaryDark = Color(0xFF610045)
val tertiaryContainerDark = Color(0xFF81005C)
val onTertiaryContainerDark = Color(0xFFFF86CA)
val errorDark = Color(0xFFEEB1FF)
val onErrorDark = Color(0xFF53006F)
val errorContainerDark = Color(0xFFAF34DD)
val onErrorContainerDark = Color(0xFFFFF6FC)
val backgroundDark = Color(0xFF16121B)
val onBackgroundDark = Color(0xFFE9DFED)
val surfaceDark = Color(0xFF141313)
val onSurfaceDark = Color(0xFFE5E2E1)
val surfaceVariantDark = Color(0xFF434749)
val onSurfaceVariantDark = Color(0xFFC3C7C9)
val outlineDark = Color(0xFF8D9193)
val outlineVariantDark = Color(0xFF434749)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE5E2E1)
val inverseOnSurfaceDark = Color(0xFF313030)
val inversePrimaryDark = Color(0xFF7D2ED8)
val surfaceDimDark = Color(0xFF141313)
val surfaceBrightDark = Color(0xFF3A3939)
val surfaceContainerLowestDark = Color(0xFF0E0E0E)
val surfaceContainerLowDark = Color(0xFF1C1B1B)
val surfaceContainerDark = Color(0xFF201F1F)
val surfaceContainerHighDark = Color(0xFF2A2A2A)
val surfaceContainerHighestDark = Color(0xFFE7AF12)
